UI tweaks
beehaw-org/ui-project pull request #37
Opened 2023-08-11 12:17 UTC by sunaurus

![image](https://github.com/beehaw-org/ui-project/assets/5356547/912bf20b-d1dd-4afa-a78a-d30f102d347a)

2023-08-12 09:01 UTC, dnswrsrx requested changes
Besides the semantic HTML and conditionally showing the banner container, everything looks good!

Banner instead of the icon in the sidebar makes a lot of sense; I figured there would have been an optional alternative image than just the icon.

The typography plugin is a nice touch. Beehaw's sidebar text is more verbose than lemm.ee's, but I think the smaller text size from the `prose` class helps.

2023-08-17 22:14 UTC, sunaurus commented on src/components/desktop-exclusive/Sidebar/MainSidebar.tsx
> +          <div className='relative w-[230px] h-[90px]'>
Good call!

2023-08-17 22:50 UTC, dnswrsrx approved these changes

2023-08-18 21:31 UTC, lionirdeadman approved these changes

2023-08-18 21:31 UTC, merged