Mockup of a navbar and a collapsible sidebar on a narrow view width
beehaw-org/ui-project pull request #38
Opened 2023-08-12 07:45 UTC by dnswrsrx

Navbar mockup from #18.

Figured the navbar could hold a button to toggle a collapsible sidebar when viewing the page on a narrow screen _e.g._ mobile, so this PR may include this feature. But I can isolate the collapsible navbar into its own PR if there's more discussion to be had about sidebar(s) in general.

PR #37 should be merged before this one gets merged.

2023-08-19 15:58 UTC, lionirdeadman requested changes
- If you open the sidebar in a small viewport and then make the viewport big again, the blur does not go away
- The sidebar could be full width when on mobile. 
- This reverts the colour change of the navbar introduced in #37, was that intentional?
- We should standardize if we use CamelCase or lowercase for component names
- Wondering if @sunaurus already has the user dropdown or something equivalent in their work on auth/login

2023-08-20 23:40 UTC, dnswrsrx commented
> If you open the sidebar in a small viewport and then make the viewport big again, the blur does not go away

Is this still happening? Try a hard refresh in case there's stale CSS (`ctrl/cmd + shift + r`). From my testing on Firefox and Chromium, it seems to be fine for me: the blur disappears when making viewport wide again with the sidebar opened.

> The sidebar could be full width when on mobile.

I made the sidebar take the full width at the narrowest break point, and 80% width at the next wider break point.

> This reverts the colour change of the navbar introduced in https://github.com/beehaw-org/ui-project/pull/37, was that intentional?

Accidentally overwrote this when rebasing.

> We should standardize if we use CamelCase or lowercase for component names

I assume you're referring to the directory of the component names - in this case `Navbar` and `Avatar`? If so, I think CamelCase makes sense, especially if we're using the `index.` file where the compiler allows us to import the directory.

Within the code however, I believe we are using CamelCase for all the components so far?

> Wondering if @sunaurus already has the user dropdown or something equivalent in their work on auth/login

If this is the case I'm happy to drop this for this PR or it can be overwritten in the following PR.

2023-08-21 01:06 UTC, lionirdeadman commented
> Is this still happening? Try a hard refresh in case there's stale CSS (ctrl/cmd + shift + r). From my testing on Firefox and Chromium, it seems to be fine for me: the blur disappears when making viewport wide again with the sidebar opened.

Yes. The way I'm testing is that I open the dev tools, make it small enough to show the sidebar button, click on it and then make the viewport wide again. It does correctly go on the side but the contents are still blurred.

> I assume you're referring to the directory of the component names - in this case Navbar and Avatar? If so, I think CamelCase makes sense, especially if we're using the index. file where the compiler allows us to import the directory.

Yeah, the folder names.

Rest LGTM, thank you

2023-08-21 22:16 UTC, dnswrsrx commented
> Yes. The way I'm testing is that I open the dev tools, make it small enough to show the sidebar button, click on it and then make the viewport wide again. It does correctly go on the side but the contents are still blurred.

I'm still not able to replicate this. Here are some screenshots of the testing I did on Firefox, I think using the way you're testing?

Here I set the width to 800px which shows the button to bring up the sidebar. I click it and the sidebar is shown with the blur occurring.

<img width="1227" alt="medium_withblur" src="https://github.com/beehaw-org/ui-project/assets/35418785/674caef6-eadc-4d75-b58c-72ebf7a8dac4">

Now, I set the width to 1100px without closing the sidebar, which should always show the sidebar and hide that button. At this point, the blur should also disappear even though the sidebar wasn't closed prior - this is the case for me as per the screenshot below. I assume this isn't the case for you? Note the `dim` class on the `article` element present between the two screenshots: it has styling for the blur, but the blur should only apply on the narrow screen widths.

<img width="1264" alt="wider_blur_off" src="https://github.com/beehaw-org/ui-project/assets/35418785/cb8c2c23-c187-4f6c-b01d-9c872108906e">

2023-08-27 15:58 UTC, sunaurus commented
>> Wondering if @sunaurus already has the user dropdown or something equivalent in their work on auth/login

>If this is the case I'm happy to drop this for this PR or it can be overwritten in the following PR.

I will rebase my branch on to this one actually 👍

2023-08-27 16:01 UTC, sunaurus approved these changes

2026-02-04 01:13 UTC, closed without merging