Add a preliminary version of the post page to build upon
beehaw-org/ui-project pull request #46
Opened 2023-08-18 06:15 UTC by lionirdeadman

This entirely reuses PostCard with no modification. It probably should but it could be used as a base to build upon and tweak.

2023-08-18 06:49 UTC, dnswrsrx requested changes

2023-08-18 06:49 UTC, dnswrsrx commented on src/app/post/[id]/page.tsx
> +import { PostView } from 'lemmy-js-client';
I would remove this `PostView` import since it's not being used

2023-08-18 06:49 UTC, dnswrsrx commented on src/app/post/[id]/page.tsx
> +const Page = async ({ params }: { params: { id: Number } }) => {
I would rename this component to `Post`, since this will be a post page.

2023-08-18 21:27 UTC, lionirdeadman commented
Fixed both comments of review

2023-08-21 21:53 UTC, dnswrsrx approved these changes

2023-08-26 11:54 UTC, sunaurus approved these changes

2023-08-26 11:55 UTC, merged